### ISSUE TITLE
Little config problem in 0.5.4

### ISSUE THREAD

**Issue by FZetting** [gvalkov/jenkins-webapi#25]
The config-property in line 60 uses
"........ or res.headers.get('content-type', '') !='application/xml'."
My jenkins unfortunately returns 'application/xml;charset=UTF-8', so the comparison with != fails.
I think it would be better to use "res.headers.get('content-type', '') .startswith(application/xml)"

And btw thanks for the lib. :-)

regards
Franz

**Comment by gvalkov** [comment]
Thanks for the catch. It's fixed in 3dd1c1b46cdb84ba22c8b9f63db012e3b28bcdfa (with your suggestion) and released in 0.5.5.
