### ISSUE TITLE
tests_require

### ISSUE THREAD

**Issue by hydrapolic** [gvalkov/jenkins-webapi#9]
setup.py declares:
'tests_require': open('requirements-dev.txt').readlines()

requirements-dev.txt:
pytest >= 2.6.3
termcolor >= 1.1.0
pytest-cov >= 1.8.0
httmock >= 1.2.2
Sphinx >= 1.2.3
alabaster >= 0.6.1

However for running tests, we don't need Sphinx nor alabaster.

**Comment by gvalkov** [comment]
Fixed in 39d01d9f50980a02167981421ed34d978a894930. Thanks.
